#!/usr/bin/env bash
set -euo pipefail

ENV_PATH="${1:-.env}"

ask_value() {
  local prompt="$1"
  local default="${2:-}"
  local value
  if [[ -n "$default" ]]; then
    read -r -p "$prompt [$default]: " value
    value="${value:-$default}"
  else
    read -r -p "$prompt: " value
  fi
  printf '%s' "$value"
}

ask_secret() {
  local prompt="$1"
  local value
  read -r -s -p "$prompt: " value
  echo
  printf '%s' "$value"
}

ask_yes_no() {
  local prompt="$1"
  local default="${2:-Y}"
  local value
  read -r -p "$prompt [$default/n]: " value
  value="${value:-$default}"
  [[ "${value,,}" =~ ^(y|yes|1|true)$ ]]
}

echo
echo "Interactive VPS .env setup"
echo "Press Enter to accept defaults when available."
echo

APP_DOMAIN="$(ask_value 'App domain' 'your-domain.example.com')"
if ask_yes_no 'Enable HTTPS with certbot' 'Y'; then
  ENABLE_HTTPS="true"
else
  ENABLE_HTTPS="false"
fi
SSL_EMAIL="$(ask_value 'SSL email for LetsEncrypt' 'admin@your-domain.example.com')"
XHS_WEB_PUBLIC_BASE_URL="$(ask_value 'Public base URL' "https://${APP_DOMAIN}")"
XHS_MCP_BASE_URL="$(ask_value 'Reachable MCP base URL for this VPS' 'http://host.docker.internal:18090')"
XHS_PUBLISHER_USER_ID="$(ask_value 'Optional publisher user_id' '')"
XHS_PUBLISHER_XSEC_TOKEN="$(ask_value 'Optional publisher xsec_token' '')"
DASHSCOPE_API_KEY="$(ask_secret 'DASHSCOPE_API_KEY')"
BAIDU_OCR_API_KEY="$(ask_secret 'BAIDU_OCR_API_KEY')"
BAIDU_OCR_SECRET_KEY="$(ask_secret 'BAIDU_OCR_SECRET_KEY')"

cat > "$ENV_PATH" <<EOF
# Generated by scripts/setup-env-vps.sh
XHS_APP_IMAGE=ghcr.io/sc6866/xiaohongshu-auto-publisher:latest
XHS_WEB_HOST=0.0.0.0
XHS_WEB_PORT=8787
APP_DOMAIN=$APP_DOMAIN
ENABLE_HTTPS=$ENABLE_HTTPS
SSL_EMAIL=$SSL_EMAIL
XHS_WEB_PUBLIC_BASE_URL=$XHS_WEB_PUBLIC_BASE_URL
XHS_MCP_BASE_URL=$XHS_MCP_BASE_URL
XHS_MCP_AUTO_START=false
XHS_PUBLISHER_USER_ID=$XHS_PUBLISHER_USER_ID
XHS_PUBLISHER_XSEC_TOKEN=$XHS_PUBLISHER_XSEC_TOKEN
DASHSCOPE_API_KEY=$DASHSCOPE_API_KEY
BAIDU_OCR_API_KEY=$BAIDU_OCR_API_KEY
BAIDU_OCR_SECRET_KEY=$BAIDU_OCR_SECRET_KEY
CF_TUNNEL_TOKEN=
EOF

echo
echo ".env generated at: $ENV_PATH"
