param(
    [string]$EnvPath = ""
)

$ErrorActionPreference = "Stop"

function Read-Secret {
    param([string]$Prompt)
    $secure = Read-Host $Prompt -AsSecureString
    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
    }
}

function Ask-Value {
    param(
        [string]$Prompt,
        [string]$Default = "",
        [switch]$Secret
    )
    if ($Secret) {
        $value = Read-Secret $Prompt
    } else {
        $suffix = ""
        if ($Default) {
            $suffix = " [$Default]"
        }
        $value = Read-Host "$Prompt$suffix"
        if ([string]::IsNullOrWhiteSpace($value)) {
            $value = $Default
        }
    }
    return $value.Trim()
}

function Ask-YesNo {
    param(
        [string]$Prompt,
        [bool]$Default = $true
    )
    $defaultText = if ($Default) { "Y/n" } else { "y/N" }
    $value = Read-Host "$Prompt [$defaultText]"
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $Default
    }
    return $value.Trim().ToLower() -in @("y", "yes", "1", "true")
}

$repoRoot = if ($EnvPath) { Split-Path -Parent $EnvPath } else { Split-Path -Parent $PSScriptRoot }
if (-not $EnvPath) {
    $EnvPath = Join-Path $repoRoot ".env"
}

Write-Host ""
Write-Host "Interactive .env setup started." -ForegroundColor Cyan
Write-Host "Press Enter to accept the default value when available." -ForegroundColor DarkGray

$enableTunnel = Ask-YesNo -Prompt "Enable Cloudflare Tunnel public access" -Default $true

$values = [ordered]@{
    "XHS_APP_IMAGE" = "ghcr.io/sc6866/xiaohongshu-auto-publisher:latest"
    "XHS_WEB_HOST" = "0.0.0.0"
    "XHS_WEB_PORT" = "8787"
    "XHS_WEB_PUBLIC_BASE_URL" = ""
    "XHS_MCP_BASE_URL" = "http://host.docker.internal:18090"
    "XHS_MCP_AUTO_START" = "false"
    "XHS_PUBLISHER_USER_ID" = ""
    "XHS_PUBLISHER_XSEC_TOKEN" = ""
    "DASHSCOPE_API_KEY" = ""
    "BAIDU_OCR_API_KEY" = ""
    "BAIDU_OCR_SECRET_KEY" = ""
    "CF_TUNNEL_TOKEN" = ""
}

$values["XHS_WEB_PUBLIC_BASE_URL"] = Ask-Value -Prompt "Public URL, leave blank if not ready yet" -Default ""
$values["XHS_MCP_BASE_URL"] = Ask-Value -Prompt "Host Xiaohongshu MCP base URL" -Default $values["XHS_MCP_BASE_URL"]
$values["XHS_PUBLISHER_USER_ID"] = Ask-Value -Prompt "Optional publisher user_id" -Default ""
$values["XHS_PUBLISHER_XSEC_TOKEN"] = Ask-Value -Prompt "Optional publisher xsec_token" -Default ""
$values["DASHSCOPE_API_KEY"] = Ask-Value -Prompt "Enter DASHSCOPE_API_KEY" -Secret
$values["BAIDU_OCR_API_KEY"] = Ask-Value -Prompt "Enter BAIDU_OCR_API_KEY" -Secret
$values["BAIDU_OCR_SECRET_KEY"] = Ask-Value -Prompt "Enter BAIDU_OCR_SECRET_KEY" -Secret

if ($enableTunnel) {
    if (-not $values["XHS_WEB_PUBLIC_BASE_URL"]) {
        $values["XHS_WEB_PUBLIC_BASE_URL"] = Ask-Value -Prompt "Tunnel is enabled, enter your public URL if available" -Default ""
    }
    $values["CF_TUNNEL_TOKEN"] = Ask-Value -Prompt "Enter Cloudflare Tunnel Token" -Secret
}

$lines = @(
    "# Generated by scripts/setup-env.ps1",
    "XHS_APP_IMAGE=$($values['XHS_APP_IMAGE'])",
    "XHS_WEB_HOST=$($values['XHS_WEB_HOST'])",
    "XHS_WEB_PORT=$($values['XHS_WEB_PORT'])",
    "XHS_WEB_PUBLIC_BASE_URL=$($values['XHS_WEB_PUBLIC_BASE_URL'])",
    "XHS_MCP_BASE_URL=$($values['XHS_MCP_BASE_URL'])",
    "XHS_MCP_AUTO_START=$($values['XHS_MCP_AUTO_START'])",
    "XHS_PUBLISHER_USER_ID=$($values['XHS_PUBLISHER_USER_ID'])",
    "XHS_PUBLISHER_XSEC_TOKEN=$($values['XHS_PUBLISHER_XSEC_TOKEN'])",
    "DASHSCOPE_API_KEY=$($values['DASHSCOPE_API_KEY'])",
    "BAIDU_OCR_API_KEY=$($values['BAIDU_OCR_API_KEY'])",
    "BAIDU_OCR_SECRET_KEY=$($values['BAIDU_OCR_SECRET_KEY'])",
    "CF_TUNNEL_TOKEN=$($values['CF_TUNNEL_TOKEN'])"
)

Set-Content -Path $EnvPath -Value $lines -Encoding UTF8
Write-Host ""
Write-Host ".env file generated: $EnvPath" -ForegroundColor Green
